name: Deploy Velocity

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    uses: AlcarisMinecraftServer/.github/.github/workflows/deploy.yml@main
    with:
      jar_name: "AlcarisChat-Velocity-*.jar"
      plugin_name: "AlcarisChat-Velocity"
      server_ids: "d7655a1d"
    secrets:
      PUFFERPANEL_URL: ${{ secrets.PUFFERPANEL_URL }}
      PUFFERPANEL_CLIENT_ID: ${{ secrets.PUFFERPANEL_CLIENT_ID }}
      PUFFERPANEL_CLIENT_SECRET: ${{ secrets.PUFFERPANEL_CLIENT_SECRET }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}